version: '3'

services:

  # REST API Server
  rest:
    container_name: rest
    build:
      context: .
      dockerfile: rest.Dockerfile
    networks:
      network:
        ipv4_address:  10.5.0.2
    ports:
      - "80:5000"
    depends_on:
      - soap

  # SOAP Server
  soap:
    container_name: soap
    build:
      context: .
      dockerfile: soap.Dockerfile
    networks:
      network:
        ipv4_address:  10.5.0.3
    ports:
      - "8000:8000"


networks:
  network:
    ipam:
      config:
        - subnet:  10.5.0.0/16
          gateway: 10.5.0.1
