version: '3'

services:

  # REST API Server
  rest:
    container_name: rest
    build:
      context: .
      dockerfile: rest.Dockerfile
    networks:
      - network
    ports:
      - "5000:5000"

  # SOAP Server
  soap:
    container_name: soap
    build:
      context: .
      dockerfile: soap.Dockerfile
    networks:
      - network

networks:
  network:
    driver: bridge
