version: '3'

services:

  # Server A
  server_a:
    container_name: server_a
    build:
      context: .
      dockerfile: server_a.Dockerfile
    networks:
      - network
    ports:
      - "5000:5000"

  # Server B
  server_b:
    container_name: server_b
    build:
      context: .
      dockerfile: server_b.Dockerfile
    networks:
      - network

networks:
  network:
    driver: bridge
